{{- if .Values.webhook.enabled -}}
{{- $altNames := list -}}
{{- $altNames = append $altNames (printf "%s-webhook" (include "aegrail-engine.fullname" .)) -}}
{{- $altNames = append $altNames (printf "%s-webhook.%s" (include "aegrail-engine.fullname" .) .Release.Namespace) -}}
{{- $altNames = append $altNames (printf "%s-webhook.%s.svc" (include "aegrail-engine.fullname" .) .Release.Namespace) -}}
{{- $altNames = append $altNames (printf "%s-webhook.%s.svc.cluster.local" (include "aegrail-engine.fullname" .) .Release.Namespace) -}}
{{- $ca := genCA "aegrail-webhook-ca" 3650 -}}
{{- $cert := genSignedCert (printf "%s-webhook" (include "aegrail-engine.fullname" .)) nil $altNames 3650 $ca -}}
{{- $_ := set .Values.webhook "_caBundle" (b64enc $ca.Cert) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegrail-engine.fullname" . }}-webhook-tls
  labels:
    {{- include "aegrail-engine.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
{{- end -}}
