package audit

import (
	"strings"
	"testing"
)

// Reference fixture: a specific Event whose SHA-256 hash was
// generated by the aegrail Python library's `compute_event_hash`
// function at v0.2.4 on 2026-05-15. The Go implementation in this
// package MUST produce the same byte sequence for the same input,
// or downstream consumers using Python to verify engine-produced
// audit logs will see chain breaks.
//
// To regenerate the expected hash:
//
//	uv run --no-project --isolated --python 3.12 --with aegrail \
//	  python -c "
//
// from aegrail import AuditEvent
// from aegrail.audit import compute_event_hash
// e = AuditEvent(
//
//	ts='2026-05-15T09:42:11.123Z',
//	session_id='sess_test_1',
//	agent_identity='egress-proxy/v1',
//	invoking_user=None,
//	principal='egress-proxy/v1@sess_test_1',
//	event='egress_denied',
//	payload={'host': 'blocked.example', 'reason': 'not_in_allowlist'},
//	budget={},
//
// )
// print(compute_event_hash(e, prev_hash=None))
//
//	"
//
// If this test ever fails after a code change to chain.go or
// canonical.go: the Go implementation has diverged from the Python
// reference. DO NOT update the expected constant; debug the
// canonical JSON encoding instead.
const pythonReferenceHash = "080c3a205943d7529fe0c6d853b0def240217be141936b16e14f6472ef00b799"

func TestComputeEventHash_MatchesPythonReference(t *testing.T) {
	t.Parallel()
	event := Event{
		Ts:            "2026-05-15T09:42:11.123Z",
		SessionID:     "sess_test_1",
		AgentIdentity: "egress-proxy/v1",
		InvokingUser:  nil,
		Principal:     "egress-proxy/v1@sess_test_1",
		EventType:     "egress_denied",
		Payload: map[string]any{
			"host":   "blocked.example",
			"reason": "not_in_allowlist",
		},
		Budget: map[string]any{},
	}

	got, err := ComputeEventHash(event, nil)
	if err != nil {
		t.Fatalf("ComputeEventHash: %v", err)
	}
	if got != pythonReferenceHash {
		t.Fatalf("Go hash diverged from Python reference.\n  got:      %s\n  expected: %s\nThe canonical JSON encoder in canonical.go has drifted; debug it, do NOT update the constant.",
			got, pythonReferenceHash)
	}

	// Determinism: same input → same hash
	got2, err := ComputeEventHash(event, nil)
	if err != nil {
		t.Fatalf("ComputeEventHash (2nd call): %v", err)
	}
	if got != got2 {
		t.Errorf("non-deterministic: %q vs %q", got, got2)
	}
}

func TestComputeEventHash_PrevHashChangesResult(t *testing.T) {
	t.Parallel()
	event := minimalEvent()

	h1, _ := ComputeEventHash(event, nil)
	prev := strings.Repeat("a", 64)
	h2, _ := ComputeEventHash(event, &prev)

	if h1 == h2 {
		t.Error("changing prev_hash must change the resulting event_hash")
	}
}

func TestComputeEventHash_PayloadChangesResult(t *testing.T) {
	t.Parallel()
	a := minimalEvent()
	b := minimalEvent()
	b.Payload = map[string]any{"host": "DIFFERENT"}

	h1, _ := ComputeEventHash(a, nil)
	h2, _ := ComputeEventHash(b, nil)

	if h1 == h2 {
		t.Error("changing payload must change the resulting event_hash")
	}
}

func TestComputeEventHash_NilPayloadEqualsEmptyPayload(t *testing.T) {
	t.Parallel()
	// nil and {} must produce identical hashes — Python's Pydantic
	// model defaults payload to {} via default_factory=dict, so a
	// missing payload is the same as an empty one.
	withNil := minimalEvent()
	withNil.Payload = nil
	withEmpty := minimalEvent()
	withEmpty.Payload = map[string]any{}

	h1, _ := ComputeEventHash(withNil, nil)
	h2, _ := ComputeEventHash(withEmpty, nil)

	if h1 != h2 {
		t.Errorf("nil payload and empty payload should hash equally: %q vs %q", h1, h2)
	}
}

func TestVerifyChain_ValidChainReturnsTrue(t *testing.T) {
	t.Parallel()
	events := buildValidChain(t, 3)
	ok, idx, err := VerifyChain(events)
	if err != nil {
		t.Fatalf("VerifyChain: %v", err)
	}
	if !ok || idx != -1 {
		t.Errorf("expected (true, -1), got (%v, %d)", ok, idx)
	}
}

func TestVerifyChain_TamperingDetectedAtCorrectIndex(t *testing.T) {
	t.Parallel()
	events := buildValidChain(t, 5)
	// Tamper with event index 2's payload but leave its event_hash
	// unchanged — verify_chain should flag exactly index 2.
	events[2].Payload = map[string]any{"host": "TAMPERED"}
	ok, idx, err := VerifyChain(events)
	if err != nil {
		t.Fatalf("VerifyChain: %v", err)
	}
	if ok || idx != 2 {
		t.Errorf("expected (false, 2), got (%v, %d)", ok, idx)
	}
}

func TestVerifyChain_EmptyChainIsValid(t *testing.T) {
	t.Parallel()
	ok, idx, err := VerifyChain(nil)
	if err != nil {
		t.Fatalf("VerifyChain: %v", err)
	}
	if !ok || idx != -1 {
		t.Errorf("empty chain: expected (true, -1), got (%v, %d)", ok, idx)
	}
}

func TestVerifyChain_FirstEventGenesisDetected(t *testing.T) {
	t.Parallel()
	// Genesis event must have prev_hash=nil. If someone constructs
	// a chain where the first event's prev_hash is non-nil, verify
	// must reject at index 0.
	events := buildValidChain(t, 2)
	wrongPrev := "deadbeef"
	events[0].PrevHash = &wrongPrev
	// Recompute event_hash with the wrong prev — actually NO, we
	// want to detect that the FIRST event's prev_hash should be
	// None. Compute the "correct" hash for the tampered event
	// (with wrongPrev as input) so the EventHash is internally
	// consistent — but then VerifyChain starts with prev=nil and
	// sees event_hash that was computed against wrongPrev. Mismatch
	// at index 0.
	h, _ := ComputeEventHash(events[0], &wrongPrev)
	events[0].EventHash = h

	ok, idx, err := VerifyChain(events)
	if err != nil {
		t.Fatalf("VerifyChain: %v", err)
	}
	if ok || idx != 0 {
		t.Errorf("expected (false, 0), got (%v, %d)", ok, idx)
	}
}

// --- helpers --------------------------------------------------------

func minimalEvent() Event {
	return Event{
		Ts:            "2026-05-15T09:42:11.123Z",
		SessionID:     "sess_min",
		AgentIdentity: "test/v1",
		Principal:     "test/v1@sess_min",
		EventType:     "engine_start",
		Payload:       map[string]any{},
		Budget:        map[string]any{},
	}
}

// buildValidChain returns n consecutive events forming a valid
// chain (each event's prev_hash points at the previous event's
// event_hash). Useful for verify_chain testing.
func buildValidChain(t *testing.T, n int) []Event {
	t.Helper()
	out := make([]Event, n)
	var prev *string
	for i := 0; i < n; i++ {
		e := Event{
			Ts:            "2026-05-15T09:42:11.123Z",
			SessionID:     "sess_chain",
			AgentIdentity: "test/v1",
			Principal:     "test/v1@sess_chain",
			EventType:     "engine_start",
			Payload:       map[string]any{"step": i},
			Budget:        map[string]any{},
		}
		if prev != nil {
			p := *prev
			e.PrevHash = &p
		}
		h, err := ComputeEventHash(e, prev)
		if err != nil {
			t.Fatalf("ComputeEventHash: %v", err)
		}
		e.EventHash = h
		prev = &h
		out[i] = e
	}
	return out
}
